version: '3'

vars:
  VERSION: v1.24.0
  COMMIT:
    sh: git rev-parse --short HEAD

tasks:
  default:
    cmds:
      - task: mac
      - task: windows
  dev:
    cmds:
      - wails dev
  mac:
    cmds:
      - wails build  -platform darwin/universal -clean -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  windows:
    cmds:
      - wails build  -platform windows/amd64 -clean -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  windebug:
    cmds:
      - wails build  -platform windows/amd64 -debug -clean
  clean:
    cmds:
      - rm -rf build/bin/twLauncher*
      - rm -rf build/bin/*.exe
