// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * AddTask
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "AddTask": (arg1, arg2) => {
        return window.go.main.App.AddTask(arg1, arg2);
      },
      /**
       * Close
       * @returns {Promise<string>}  - Go Type: string
       */
      "Close": () => {
        return window.go.main.App.Close();
      },
      /**
       * DelTask
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "DelTask": (arg1) => {
        return window.go.main.App.DelTask(arg1);
      },
      /**
       * GetDataStore
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetDataStore": () => {
        return window.go.main.App.GetDataStore();
      },
      /**
       * GetInfo
       * @returns {Promise<TWLanuncherInfo>}  - Go Type: main.TWLanuncherInfo
       */
      "GetInfo": () => {
        return window.go.main.App.GetInfo();
      },
      /**
       * GetTWPCAP
       * @returns {Promise<TWPCAPInfo>}  - Go Type: main.TWPCAPInfo
       */
      "GetTWPCAP": () => {
        return window.go.main.App.GetTWPCAP();
      },
      /**
       * GetTWSNMP
       * @returns {Promise<TWSNMPInfo>}  - Go Type: main.TWSNMPInfo
       */
      "GetTWSNMP": () => {
        return window.go.main.App.GetTWSNMP();
      },
      /**
       * GetTWWifiScan
       * @returns {Promise<TWWifiScanInfo>}  - Go Type: main.TWWifiScanInfo
       */
      "GetTWWifiScan": () => {
        return window.go.main.App.GetTWWifiScan();
      },
      /**
       * GetTWWinLog
       * @returns {Promise<TWWinLogInfo>}  - Go Type: main.TWWinLogInfo
       */
      "GetTWWinLog": () => {
        return window.go.main.App.GetTWWinLog();
      },
      /**
       * Start
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Start": (arg1, arg2) => {
        return window.go.main.App.Start(arg1, arg2);
      },
      /**
       * Stop
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Stop": (arg1) => {
        return window.go.main.App.Stop(arg1);
      },
    },
  },

};
export default go;
