// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * Close
       * @returns {Promise<string>}  - Go Type: string
       */
      "Close": () => {
        return window.go.main.App.Close();
      },
      /**
       * GetDataStore
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetDataStore": () => {
        return window.go.main.App.GetDataStore();
      },
      /**
       * GetInfo
       * @returns {Promise<TWLanuncherInfo>}  - Go Type: main.TWLanuncherInfo
       */
      "GetInfo": () => {
        return window.go.main.App.GetInfo();
      },
    },
  },

};
export default go;
