// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * AddTask
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "AddTask": (arg1, arg2) => {
        return window.go.main.App.AddTask(arg1, arg2);
      },
      /**
       * Close
       * @returns {Promise<string>}  - Go Type: string
       */
      "Close": () => {
        return window.go.main.App.Close();
      },
      /**
       * DelTask
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "DelTask": (arg1) => {
        return window.go.main.App.DelTask(arg1);
      },
      /**
       * GetDataStore
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetDataStore": () => {
        return window.go.main.App.GetDataStore();
      },
      /**
       * GetInfo
       * @returns {Promise<LanuncherInfo>}  - Go Type: main.LanuncherInfo
       */
      "GetInfo": () => {
        return window.go.main.App.GetInfo();
      },
      /**
       * GetProcessInfo
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<ProcessInfo>}  - Go Type: main.ProcessInfo
       */
      "GetProcessInfo": (arg1) => {
        return window.go.main.App.GetProcessInfo(arg1);
      },
      /**
       * Start
       * @param {string} arg1 - Go Type: string
       * @param {Array<string>} arg2 - Go Type: []string
       * @param {boolean} arg3 - Go Type: bool
       * @returns {Promise<string>}  - Go Type: string
       */
      "Start": (arg1, arg2, arg3) => {
        return window.go.main.App.Start(arg1, arg2, arg3);
      },
      /**
       * Stop
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Stop": (arg1) => {
        return window.go.main.App.Stop(arg1);
      },
    },
  },

};
export default go;
